name: partitura_example
description: Demo app for the partitura music notation library.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  partitura:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
