// Regenerates `lib/src/embedded_metadata.dart` from the Bravura SMuFL metadata
// so the standalone CLI can render offline without the repo checkout.
//
//   dart run tool/embed_metadata.dart      (from the partitura_cli package)
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:partitura_core/partitura_core.dart';

void main() {
  final src = File('../partitura/assets/smufl/bravura_metadata.json');
  if (!src.existsSync()) {
    stderr.writeln('metadata not found at ${src.path}');
    exit(1);
  }
  final bytes = src.readAsBytesSync();
  final b64 = base64Encode(deflate(Uint8List.fromList(bytes)));
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/embed_metadata.dart — do not edit by hand.')
    ..writeln('//')
    ..writeln('// The bundled Bravura SMuFL metadata, DEFLATE-compressed and')
    ..writeln('// base64-encoded, so the standalone `partitura` binary can')
    ..writeln('// render offline without the repo. Decoded by')
    ..writeln('// `embeddedBravuraMetadataJson()`.')
    ..writeln('library;')
    ..writeln()
    ..writeln('const String bravuraMetadataDeflatedBase64 =')
    ..writeln("    '$b64';");
  File('lib/src/embedded_metadata.dart').writeAsStringSync(out.toString());
  stdout.writeln('embedded ${bytes.length} B → ${b64.length} base64 chars');
}
