/// SMuFL glyph name → codepoint table for the glyphs partitura draws.
///
/// Codepoints follow the SMuFL specification
/// (https://w3c.github.io/smufl/latest/) and are identical in every
/// compliant font, including the bundled Bravura.
library;

/// Maps the SMuFL glyph names emitted by the layout engine (see
/// `SmuflGlyph` in `partitura_core`) to the character to draw.
const Map<String, String> smuflCodepoints = {
  'gClef': '\uE050',
  'fClef': '\uE062',
  'cClef': '\uE05C',
  'noteheadWhole': '\uE0A2',
  'noteheadHalf': '\uE0A3',
  'noteheadBlack': '\uE0A4',
  'flag8thUp': '\uE240',
  'flag8thDown': '\uE241',
  'flag16thUp': '\uE242',
  'flag16thDown': '\uE243',
  'restWhole': '\uE4E3',
  'restHalf': '\uE4E4',
  'restQuarter': '\uE4E5',
  'rest8th': '\uE4E6',
  'rest16th': '\uE4E7',
  'accidentalFlat': '\uE260',
  'accidentalNatural': '\uE261',
  'accidentalSharp': '\uE262',
  'accidentalDoubleSharp': '\uE263',
  'accidentalDoubleFlat': '\uE264',
  'augmentationDot': '\uE1E7',
  'timeSig0': '\uE080',
  'timeSig1': '\uE081',
  'timeSig2': '\uE082',
  'timeSig3': '\uE083',
  'timeSig4': '\uE084',
  'timeSig5': '\uE085',
  'timeSig6': '\uE086',
  'timeSig7': '\uE087',
  'timeSig8': '\uE088',
  'timeSig9': '\uE089',
  'tuplet0': '\uE880',
  'tuplet1': '\uE881',
  'tuplet2': '\uE882',
  'tuplet3': '\uE883',
  'tuplet4': '\uE884',
  'tuplet5': '\uE885',
  'tuplet6': '\uE886',
  'tuplet7': '\uE887',
  'tuplet8': '\uE888',
  'tuplet9': '\uE889',
  'articAccentAbove': '\uE4A0',
  'articAccentBelow': '\uE4A1',
  'articStaccatoAbove': '\uE4A2',
  'articStaccatoBelow': '\uE4A3',
  'articTenutoAbove': '\uE4A4',
  'articTenutoBelow': '\uE4A5',
  'articMarcatoAbove': '\uE4AC',
  'articMarcatoBelow': '\uE4AD',
  'fermataAbove': '\uE4C0',
  'fermataBelow': '\uE4C1',
  'gClef8va': '\uE053',
  'gClef8vb': '\uE052',
  'fClef8vb': '\uE064',
  'ornamentTrill': '\uE566',
  'ornamentTurn': '\uE567',
  'ornamentShortTrill': '\uE56C',
  'ornamentMordent': '\uE56D',
  'dynamicPP': '\uE52B',
  'dynamicPiano': '\uE520',
  'dynamicMP': '\uE52C',
  'dynamicMF': '\uE52D',
  'dynamicForte': '\uE522',
  'dynamicFF': '\uE52F',
  'noteheadDoubleWhole': '\uE0A0',
  'flag32ndUp': '\uE244',
  'flag32ndDown': '\uE245',
  'flag64thUp': '\uE246',
  'flag64thDown': '\uE247',
  'restDoubleWhole': '\uE4E2',
  'rest32nd': '\uE4E8',
  'rest64th': '\uE4E9',
  'repeatDots': '\uE043',
  'brace': '\uE000',
  'segno': '\uE047',
  'coda': '\uE048',
  'fingering0': '\uED10',
  'fingering1': '\uED11',
  'fingering2': '\uED12',
  'fingering3': '\uED13',
  'fingering4': '\uED14',
  'fingering5': '\uED15',
  'fingering6': '\uED16',
  'fingering7': '\uED17',
  'fingering8': '\uED18',
  'fingering9': '\uED19',
  'wiggleArpeggiatoUp': '\uEAA9',
  'wiggleArpeggiatoUpArrow': '\uEAAD',
  'wiggleArpeggiatoDownArrow': '\uEAAE',
};
